openapi: '3.0.2'
info:
  title: Shopping Cart RESTful API
  description: API Spec for Shopping Cart RESTful API
  version: '1.0'
servers:
  - url: http://localhost:3000/api
paths:
  /products:
    get:
      description: List All Products
      summary: List All Products
      tags:
        - "Products API"
      responses:
        '200':
          description: Success get all products
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
  /cart:
    post:
      description: Create new cart
      summary: Create new cart
      tags:
        - "Cart API"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sku:
                  type: string
                name:
                  type: string
                price:
                  type: number
                qty:
                  type: number
      responses:
        '201':
          description: Success create cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/Product'
  /checkout:
    post:
      description: Create checkout
      summary: Create checkout
      tags:
        - "Checkout API"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sku:
                  type: string
                qty:
                  type: number
      responses:
        '201':
          description: Success checkout
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        sku:
                          type: string
                        qty:
                          type: number
components:
  schemas:
    Product:
      type: object
      properties:
        sku:
          type: string
        name:
          type: string
        price:
          type: number
        qty:
          type: number